version: '3'

services:
  contosouniversity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - contosonet
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=contosouniversity
      - POSTGRES_PASSWORD=contosouniversity
      - POSTGRES_DB=contosouniversity
    volumes:
      - contosopg:/var/lib/postgresql
    networks:
      - contosonet
volumes:
  contosopg:
    driver: local
networks:
  contosonet: